# Generated by Django 5.0.4 on 2024-04-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecognitionEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=255)),
                ('savedFileName', models.CharField(max_length=255)),
                ('uploadDateAndTime', models.DateTimeField()),
                ('recognizedNames', models.CharField(max_length=255)),
                ('nextAction', models.CharField(max_length=255)),
            ],
        ),
    ]
